"""empty message

Revision ID: 8ebd9ed9b6b1
Revises: 
Create Date: 2020-01-03 03:05:31.432382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ebd9ed9b6b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('car',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('make', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('registry', sa.String(length=12), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_make'), 'car', ['make'], unique=False)
    op.create_index(op.f('ix_car_model'), 'car', ['model'], unique=False)
    op.create_index(op.f('ix_car_power'), 'car', ['power'], unique=False)
    op.create_index(op.f('ix_car_registry'), 'car', ['registry'], unique=True)
    op.create_index(op.f('ix_car_year'), 'car', ['year'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_description'), 'service', ['description'], unique=False)
    op.create_index(op.f('ix_service_name'), 'service', ['name'], unique=False)
    op.create_index(op.f('ix_service_price'), 'service', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_price'), table_name='service')
    op.drop_index(op.f('ix_service_name'), table_name='service')
    op.drop_index(op.f('ix_service_description'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_car_year'), table_name='car')
    op.drop_index(op.f('ix_car_registry'), table_name='car')
    op.drop_index(op.f('ix_car_power'), table_name='car')
    op.drop_index(op.f('ix_car_model'), table_name='car')
    op.drop_index(op.f('ix_car_make'), table_name='car')
    op.drop_table('car')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
